// Code generated by bpf2go; DO NOT EDIT.

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	TracerMapEvents              = "events"
	TracerProgKprobeTcpV4Connect = "kprobe_tcp_v4_connect"
)

// LoadTracer returns the embedded CollectionSpec for Tracer.
func LoadTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Tracer: %w", err)
	}

	return spec, err
}

// LoadTracerObjects loads Tracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TracerObjects
//	*TracerPrograms
//	*TracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTracerObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TracerSpecs struct {
	TracerProgramSpecs
	TracerMapSpecs
	TracerVariableSpecs
}

// TracerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TracerProgramSpecs struct {
	KprobeTcpV4Connect *ebpf.ProgramSpec `ebpf:"kprobe_tcp_v4_connect"`
}

// TracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TracerMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// TracerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TracerVariableSpecs struct {
}

// TracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type TracerObjects struct {
	TracerPrograms
	TracerMaps
	TracerVariables
}

func (o *TracerObjects) Close() error {
	return _TracerClose(
		&o.TracerPrograms,
		&o.TracerMaps,
	)
}

// TracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type TracerMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *TracerMaps) Close() error {
	return _TracerClose(
		m.Events,
	)
}

// TracerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type TracerVariables struct {
}

// TracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type TracerPrograms struct {
	KprobeTcpV4Connect *ebpf.Program `ebpf:"kprobe_tcp_v4_connect"`
}

func (p *TracerPrograms) Close() error {
	return _TracerClose(
		p.KprobeTcpV4Connect,
	)
}

func _TracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tracer_bpf.o
var _TracerBytes []byte
